/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package playingfield;

import java.awt.event.WindowEvent;

import playingfield.PlayingField;

/**
 *
 * @author laurin.agostini
 */
public class AgainWindow extends javax.swing.JFrame {
	private PlayingField playingField;
    /**
     * Creates new form HelpPage
     */
    public AgainWindow(PlayingField playingField) {
		this.playingField = playingField;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

		this.setSize(200, 100);
        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Play again?");
		
		againButton = new javax.swing.JButton();
        againButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        againButton.setText("Again");
        againButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                againButtonMouseClicked(evt);
            }
        });
		
		quitButton = new javax.swing.JButton();
		quitButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        quitButton.setText("Quit");
        quitButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                quitButtonMouseClicked(evt);
            }
        });

        

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createSequentialGroup()
            .addComponent(againButton)
			.addComponent(quitButton)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup()
            .addComponent(againButton)
			.addComponent(quitButton)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
	
	private void againButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuExitClicked
		playingField.again(true);
		this.dispatchEvent(new WindowEvent(this, WindowEvent.WINDOW_CLOSING));
    }
	
    private void quitButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuExitClicked
		playingField.again(false);
		this.dispatchEvent(new WindowEvent(this, WindowEvent.WINDOW_CLOSING));
    }//GEN-LAST:event_jMenuExitClicked

    /**
     * 
     */
    /*public static void main(String args[]) {
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HelpWindow().setVisible(true);
            }
        });
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton againButton;
	private javax.swing.JButton quitButton;
    // End of variables declaration//GEN-END:variables
}
