/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package playingfield;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JPanel;
import javax.swing.JScrollPane;

/**
 *
 * @author laurin.agostini
 */
public class PlayingField extends JPanel {

    JPanel history;
    int historyCount = 0;
    int codeLength = 4;
    String lastCode = "";
    String colors;
    
    Color[] colorTable = {Color.RED, Color.BLUE, Color.GREEN, Color.YELLOW};
    //String currentCode = "aaaa";
    JComboBox[] comboBoxes;
    /**
     * Creates new form PlayingField
     */
    public PlayingField(String colors, int codeLength) {
        this.colors = colors;
        this.codeLength = codeLength;
        comboBoxes = new JComboBox[codeLength];
        initComponents();
        initActivePane();
        initHistory();
        System.out.println("PlayingField created with " + getComponentCount() + " components");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        activePane = new javax.swing.JPanel();
        addButton = new javax.swing.JButton();
        historyPane = new javax.swing.JPanel();

        activePane.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        activePane.setPreferredSize(new java.awt.Dimension(426, 67));

        addButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        addButton.setText("Send");
        addButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout activePaneLayout = new javax.swing.GroupLayout(activePane);
        activePane.setLayout(activePaneLayout);
        activePaneLayout.setHorizontalGroup(
            activePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, activePaneLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(addButton)
                .addGap(18, 18, 18))
        );
        activePaneLayout.setVerticalGroup(
            activePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, activePaneLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(addButton)
                .addGap(457, 457, 457))
        );

        historyPane.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout historyPaneLayout = new javax.swing.GroupLayout(historyPane);
        historyPane.setLayout(historyPaneLayout);
        historyPaneLayout.setHorizontalGroup(
            historyPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        historyPaneLayout.setVerticalGroup(
            historyPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(activePane, javax.swing.GroupLayout.DEFAULT_SIZE, 435, Short.MAX_VALUE)
            .addComponent(historyPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(activePane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(historyPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addButtonMouseClicked
        String code = "";
        for(int i = 0; i < codeLength; ++i){
            code += comboBoxes[i].getSelectedItem();
        }
        String response = "";

        //response = client.sendCode(code);
        lastCode = code;
        addToHistory(code, response);
        addButton.setEnabled(false);
    }//GEN-LAST:event_addButtonMouseClicked

    
    private Color charToColorResponse(char input){
        if(input == 'B'){
            return Color.black;
        }
        return Color.white;
        
    }
    
    private JPanel getListEntryRendered(String code, String response, int index){
        JPanel entry = new JPanel();
        entry.add(new JLabel(((Integer)(index)).toString()));
        
        for(int i = 0; i < code.length(); ++i){
            JButton button = new JButton(code.substring(i, i+1));
            button.setBackground(ComboBoxRenderer.charToColor(code.charAt(i)));
            button.setEnabled(false);
            button.setSize(20, 20);
            button.setLocation(i*20, 0);
            entry.add(button);
        }
        for(int i = 0; i < response.length(); ++i){
            JButton button = new JButton(response.substring(i, i+1));
            button.setBackground(charToColorResponse(response.charAt(i)));
            button.setEnabled(false);
            button.setSize(20, 20);
            button.setLocation(i*20, 0);
            entry.add(button);
        }
        return entry;
    }
    
    private void addToHistory(String code, String response){
        historyCount++;
        GridBagConstraints gbc = new GridBagConstraints();
        gbc.gridwidth = GridBagConstraints.REMAINDER;
        gbc.weightx = 1;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        history.add(getListEntryRendered(code, response, historyCount), gbc, 0);
        revalidate();
    }
    
    private void initHistory(){
        historyPane.setLayout(new BorderLayout());
        historyPane.setPreferredSize(new java.awt.Dimension(400, 400));

        history = new JPanel(new GridBagLayout());
        GridBagConstraints gbc = new GridBagConstraints();
        gbc.gridwidth = GridBagConstraints.REMAINDER;
        gbc.weightx = 1;
        gbc.weighty = 1;
        //history.add(new JPanel(), gbc);
        historyPane.add(new JScrollPane(history));
        revalidate();
    }
    
    private void initActivePane(){
        String[] array = colors.split("(?!^)");
        for(int i = 0; i < codeLength; ++i){
            JComboBox comboBox = new JComboBox(array);
            comboBox.setBackground(ComboBoxRenderer.charToColor(colors.charAt(0)));
            comboBox.setSize(40, 40);
            comboBox.setLocation(i*50, 0);
            comboBox.setRenderer(new ComboBoxRenderer());
            comboBox.addItemListener(new ItemChangeListener(this));
            activePane.add(comboBox);
            comboBoxes[i] = comboBox;
        }
        revalidate();
    }
    
    public void codeChanged(){
        addButton.setEnabled(true);
        String code = "";
        for(int i = 0; i < codeLength; ++i){
            code += comboBoxes[i].getSelectedItem();
        }
        System.out.println("Code: " + code + " lastCode: " + lastCode);
        if(code.equals(lastCode)){
            addButton.setEnabled(false);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel activePane;
    private javax.swing.JButton addButton;
    private javax.swing.JPanel historyPane;
    // End of variables declaration//GEN-END:variables
}
